version: 2
jobs:

  build_and_test:
    
    working_directory: ~/hello-mvn-obj

    docker:
      - image: circleci/openjdk:8-jdk-browsers

    steps:

      - checkout

      - restore_cache:
          key: hello-mvn-obj-{{ checksum "pom.xml" }}
      
      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: hello-mvn-obj-{{ checksum "pom.xml" }}
      
      - run: mvn clean package -Pdev -DskipTests
      
      - store_test_results:
          path: target/surefire-reports
      
      - store_artifacts:
          path: target/hello-mvn-obj.jar

     - setup_remote_docker

     - run:
         # name: Start container and verify is it's working?
         command: |
           set -x
           docker build -t appmanagm/hello:0.0.${CIRCLE_BUILD_NUM} .
            
     - run:
         # name: Push Images
         command: |
           docker login -u $DOCKER_USER -p $DOCKER_PASS
           docker push appmanagm/hello:0.0.${CIRCLE_BUILD_NUM}