version: 2
jobs:
  build:
    
    working_directory: ~/hello-mvn-obj

    docker:
      - image: circleci/openjdk:8-jdk-browsers

    steps:

      - checkout

      - restore_cache:
          key: hello-mvn-obj-{{ checksum "pom.xml" }}
      
     # - run: mvn install:install-file -DgroupId=com.hello -DartifactId=hello -Dversion=9.1.2 -Dpackaging=jar -Dfile=asset/lib/hello.jar
      
      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: hello-mvn-obj-{{ checksum "pom.xml" }}
      
      - run: mvn clean package -DskipTests
      
      - store_test_results:
          path: target/surefire-reports
      
      - store_artifacts:
          path: target/hello-mvn-obj.jar

     - run: echo $DOCKER_USER
  #   - run: docker login -u $DOCKER_USER -p $DOCKER_PASS


   #  - run : docker run -d --name db appmanagm/hello:v0.3
         

     # build the application image
    # - run: docker build -t appmanagm/hello:$CIRCLE_BRANCH .

     # deploy the image
    # - run: docker push appmanagm/hello:$CIRCLE_BRANCH

