version: 2
jobs:
  build:
    
    working_directory: ~/hello-mvn-obj

    docker:
      - image: circleci/openjdk:8-jdk-browsers

    steps:

      - checkout

      - restore_cache:
          key: pdflib-mvn-obj-{{ checksum "pom.xml" }}
      
      - run: mvn install:install-file -DgroupId=com.hello -DartifactId=hello -Dversion=9.1.2 -Dpackaging=jar -Dfile=asset/lib/hello.jar
      
      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: pdflib-mvn-obj-{{ checksum "pom.xml" }}
      
      - run: mvn clean package -DskipTests
      
      - store_test_results:
          path: target/surefire-reports
      
      - store_artifacts:
          path: target/hello-mvn-obj.jar

